{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat build of Quarkus",
      "fix_state": "Under investigation",
      "package_name": "quarkus-jdbc-postgresql",
      "cpe": "cpe:/a:redhat:openshift_application_runtimes"
    },
    {
      "product_name": "Red Hat build of Quarkus",
      "fix_state": "Under investigation",
      "package_name": "quarkus-jdbc-postgresql-deployment",
      "cpe": "cpe:/a:redhat:openshift_application_runtimes"
    },
    {
      "product_name": "Red Hat Integration Camel K",
      "fix_state": "Under investigation",
      "package_name": "quarkus-jdbc-postgresql",
      "cpe": "cpe:/a:redhat:integration:1"
    },
    {
      "product_name": "Red Hat Integration Camel K",
      "fix_state": "Under investigation",
      "package_name": "quarkus-jdbc-postgresql-deployment",
      "cpe": "cpe:/a:redhat:integration:1"
    },
    {
      "product_name": "Red Hat JBoss Fuse 7",
      "fix_state": "Under investigation",
      "package_name": "quarkus-jdbc-postgresql",
      "cpe": "cpe:/a:redhat:jboss_fuse:7"
    },
    {
      "product_name": "Red Hat JBoss Fuse 7",
      "fix_state": "Under investigation",
      "package_name": "quarkus-jdbc-postgresql-deployment",
      "cpe": "cpe:/a:redhat:jboss_fuse:7"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2020-06-04T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-13692 jdbc-postgresql: XXE vulnerability",
    "id": "1852985",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1852985"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "9.8",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-611",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-13692",
  "document_distribution": "",
  "details": [
    "PostgreSQL JDBC Driver (aka PgJDBC) before 42.2.13 allows XXE."
  ],
  "references": null
}