{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Affected",
      "package_name": "unbound",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Affected",
      "package_name": "unbound",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "unbound",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2020-05-19T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-12663 unbound: infinite loop via malformed DNS answers received from upstream servers",
    "id": "1837604",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1837604"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20-\u003eCWE-835",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-12663",
  "document_distribution": "",
  "details": [
    "Unbound before 1.10.1 has an infinite loop via malformed DNS answers received from upstream servers."
  ],
  "references": null
}