{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ceph Storage 2",
      "fix_state": "Under investigation",
      "package_name": "python-rtslib",
      "cpe": "cpe:/a:redhat:ceph_storage:2"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "python-rtslib",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Affected",
      "package_name": "python-rtslib",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python-rtslib",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-06-19T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-14019 python-rtslib: weak permissions for /etc/target/saveconfig.json",
    "id": "1854723",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1854723"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.3",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-282",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-14019",
  "document_distribution": "",
  "details": [
    "Open-iSCSI rtslib-fb through 2.1.72 has weak permissions for /etc/target/saveconfig.json because shutil.copyfile (instead of shutil.copy) is used, and thus permissions are not preserved."
  ],
  "references": null
}