{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-13596"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://docs.djangoproject.com/en/3.0/releases/security/",
          "refsource": "MISC",
          "tags": [],
          "url": "https://docs.djangoproject.com/en/3.0/releases/security/"
        },
        {
          "name": "https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
          "refsource": "MISC",
          "tags": [],
          "url": "https://groups.google.com/forum/#!msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ"
        },
        {
          "name": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-06-03T14:25Z",
  "publishedDate": "2020-06-03T14:15Z"
}