{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-10177"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Pillow before 6.2.3 and 7.x before 7.0.1 has multiple out-of-bounds reads in libImaging/FliDecode.c."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/python-pillow/Pillow/commits/master/src/libImaging",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/python-pillow/Pillow/commits/master/src/libImaging"
        },
        {
          "name": "https://github.com/python-pillow/Pillow/pull/4503",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/python-pillow/Pillow/pull/4503"
        },
        {
          "name": "https://github.com/python-pillow/Pillow/pull/4538",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/python-pillow/Pillow/pull/4538"
        },
        {
          "name": "https://pillow.readthedocs.io/en/stable/releasenotes/6.2.3.html",
          "refsource": "MISC",
          "tags": [],
          "url": "https://pillow.readthedocs.io/en/stable/releasenotes/6.2.3.html"
        },
        {
          "name": "https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html",
          "refsource": "MISC",
          "tags": [],
          "url": "https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-06-25T19:31Z",
  "publishedDate": "2020-06-25T19:15Z"
}