{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:hp:hpe_iot_\\+_gcp:1.2.4.2:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:hp:hpe_iot_\\+_gcp:1.4.0:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:hp:hpe_iot_\\+_gcp:1.4.1:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:hp:hpe_iot_\\+_gcp:1.4.2:*:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-7133"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "product": {
              "product_data": [
                {
                  "product_name": "hpe_iot_+_gcp",
                  "version": {
                    "version_data": [
                      {
                        "version_affected": "=",
                        "version_value": "1.2.4.2"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.4.0"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.4.1"
                      },
                      {
                        "version_affected": "=",
                        "version_value": "1.4.2"
                      }
                    ]
                  }
                }
              ]
            },
            "vendor_name": "hp"
          }
        ]
      }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A unauthorized remote access vulnerability was discovered in HPE IOT + GCP version(s): 1.4.0, 1.4.1, 1.4.2, 1.2.4.2."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-862"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US\u0026docId=emr_na-hpesbhf03947en_us",
          "refsource": "MISC",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://support.hpe.com/hpsc/doc/public/display?docLocale=en_US\u0026docId=emr_na-hpesbhf03947en_us"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 7.5,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 10,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "HIGH",
      "userInteractionRequired": false
    }
  },
  "lastModifiedDate": "2020-05-04T21:07Z",
  "publishedDate": "2020-04-24T19:15Z"
}