{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:openldap:openldap:*:*:*:*:*:*:*:*",
            "versionEndExcluding": "2.4.46-10.el8",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      },
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-15719"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "libldap in certain third-party OpenLDAP packages has a certificate-validation flaw when the third-party package is asserting RFC6125 support. It considers CN even when there is a non-matching subjectAltName (SAN). This is fixed in, for example, openldap-2.4.46-10.el8 in Red Hat Enterprise Linux."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-295"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://access.redhat.com/errata/RHBA-2019:3674",
          "refsource": "MISC",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "https://access.redhat.com/errata/RHBA-2019:3674"
        },
        {
          "name": "https://bugs.openldap.org/show_bug.cgi?id=9266",
          "refsource": "MISC",
          "tags": [
            "Permissions Required",
            "Vendor Advisory"
          ],
          "url": "https://bugs.openldap.org/show_bug.cgi?id=9266"
        },
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1740070",
          "refsource": "MISC",
          "tags": [
            "Issue Tracking",
            "Third Party Advisory"
          ],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1740070"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 7.5,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 10,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "HIGH",
      "userInteractionRequired": false
    },
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "HIGH",
        "baseScore": 9.8,
        "baseSeverity": "CRITICAL",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "version": "3.1"
      },
      "exploitabilityScore": 3.9,
      "impactScore": 5.9
    }
  },
  "lastModifiedDate": "2020-07-21T17:54Z",
  "publishedDate": "2020-07-14T14:15Z"
}