{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-6937"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A Denial of Service vulnerability in MuleSoft Mule CE/EE 3.8.x, 3.9.x, and 4.x released before April 7, 2020, could allow remote attackers to submit data which can lead to resource exhaustion."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://help.salesforce.com/articleView?id=000353701\u0026language=en_US\u0026type=1\u0026mode=1",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://help.salesforce.com/articleView?id=000353701\u0026language=en_US\u0026type=1\u0026mode=1"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-05-30T12:32Z",
  "publishedDate": "2020-05-29T22:15Z"
}