{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-12850"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Pydio Cells Enterprise OVF version 2.0.4 has insecure permissions that could allow local privilege escalation."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://www.coresecurity.com/advisories",
          "refsource": "MISC",
          "tags": [],
          "url": "https://www.coresecurity.com/advisories"
        },
        {
          "name": "https://www.coresecurity.com/core-labs/advisories/pydio-cells-204-multiple-vulnerabilities",
          "refsource": "MISC",
          "tags": [],
          "url": "https://www.coresecurity.com/core-labs/advisories/pydio-cells-204-multiple-vulnerabilities"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-06-11T02:15Z",
  "publishedDate": "2020-06-11T02:15Z"
}