{
  "debianbug": 796104,
  "description": "The (1) contrib.sessions.backends.base.SessionBase.flush and (2) cache_db.SessionStore.flush functions in Django 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions create empty sessions in certain circumstances, which allows remote attackers to cause a denial of service (session store consumption) via unspecified vectors.",
  "releases": {
    "bullseye": {
      "fixed_version": "1.7.10-1",
      "repositories": {
        "bullseye": "2:2.2.12-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "fixed_version": "1.7.10-1",
      "repositories": {
        "buster": "1:1.11.28-1~deb10u1",
        "buster-security": "1:1.11.28-1~deb10u1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "jessie": {
      "fixed_version": "1.7.7-1+deb8u2",
      "repositories": {
        "jessie": "1.7.11-1+deb8u3",
        "jessie-security": "1.7.11-1+deb8u9"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "1.7.10-1",
      "repositories": {
        "sid": "2:2.2.13-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "1.7.10-1",
      "repositories": {
        "stretch": "1:1.10.7-2+deb9u7",
        "stretch-security": "1:1.10.7-2+deb9u8"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    }
  },
  "scope": "local"
}